<?php
/**
 * Wagento Have I Been Pwned?
 *
 * Adds test to built-in password strength indicator to check if password has
 * been used on other sites.
 *
 * @package Wagento\HIBP\Controller\Index
 * @author Joseph Leedy <joseph@wagento.com>, Chirag Dodia <chirag.dodia@wagento.com>
 * @copyright Copyright (c) Wagento Creative LLC. (https://www.wagento.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Wagento\HIBP\Block\Adminhtml\User $block */
?>
<?php
$mode = $block->getConfig('hibp/general/mode');
?>
<?php $scriptString = <<<script

require([
        "jquery",
        "domReady",
        'Wagento_HIBP/js/hibp'
    ], function($, domReady, hibp){

        domReady(function () {
            $("#user_password").on("change", function(){
                var mode = '<?= $mode ?>';
                var validText = '<label class="mage-error"><div id="hibp-count" class="hibp-count mage-error" data-role="hibp-count" aria-live="polite" generated="false">';

                password = $(this).val();
                hibp(password, function (result) {
                    validText += 'This password has been used <span class="hibp-count-label" data-role="hibp-count-label">' + result.count  +'</span> times on other sites.';
                    validText += '(Source: <a href="https://haveibeenpwned.com/" target="_blank">HaveIBeenPwned.com</a>)';
                    validText += '</div></label>';
                    if (result.count > 0) {
                        if (mode === 'restrict') {
                            validText +='<span class="hibp-strict-message" data-role="hibp-strict-message">Please choose another password.</span>';
                            $('#save').prop('disabled', true);
                        } else {
                            $('#save').prop('disabled', false);
                        }
                        $(validText).insertAfter($("#user_password"));
                    }
                });
            });
        });
    });

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script>
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
    })
</script>
