<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Wagento\HIBP\Block\Adminhtml\User $block */
?>
<?php $scriptString = <<<script

require([
    "jquery",
    "domReady",
    'Wagento_HIBP/js/hibp'
], function($, domReady, hibp){

    domReady(function () {
        $("#user_password").on("change", function(){
            password = $(this).val();
             hibp(password, function (result) {
                alert(result.count);
            });
        });
    });

});

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script>
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
    })
</script>
